# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import NoSuchElementException, TimeoutException

class TestChange():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.wait = WebDriverWait(self.driver, 10)  # 10 seconds timeout
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_change(self):
    # Navigate to the home page
    self.driver.get("http://localhost/Exam/index.html")
    self.driver.set_window_size(1552, 832)
    
    # Click on login button
    self.driver.find_element(By.CSS_SELECTOR, ".logbtn").click()
    
    # Wait for login form to be visible
    self.wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, "#signinForm")))
    
    # Fill in login credentials
    self.driver.find_element(By.CSS_SELECTOR, "#signinForm input[type='email']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signinForm input[type='email']").send_keys("abin37523@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, "#signinForm input[type='password']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signinForm input[type='password']").send_keys("Owner123")
    
    # Submit login form
    self.driver.find_element(By.CSS_SELECTOR, "#signinForm button[type='submit']").click()
    
    # Wait for login to complete and redirect to dashboard
    time.sleep(3)  # Give time for redirect
    
    # Print current URL for debugging
    print(f"Current URL after login: {self.driver.current_url}")
    
    # Try to find and click the edit button
    try:
        edit_button = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".fa-edit")))
        edit_button.click()
        
        # Wait for the form to load
        time.sleep(2)
        
        # Update the afternoon rate
        afternoon_rate = self.wait.until(EC.presence_of_element_located((By.ID, "afternoon_rate")))
        afternoon_rate.clear()
        afternoon_rate.send_keys("800.00")
        
        # Submit the form
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        
    except Exception as e:
        print(f"Error: {str(e)}")
        # Take a screenshot for debugging
        self.driver.save_screenshot("error_screenshot.png")
        raise
  
